import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <main className="container mx-auto px-4 mt-6">
            <div className="flex justify-end py-4">
              <div className="w-fit">
                <UserButton />
              </div>
            </div>
            <Toaster
              position="top-center"
              reverseOrder={true}
              toastOptions={{ className: "w-full" }}
            />
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
